// Mocks generated by Mockito 5.4.6 from annotations
// in word_learn_app/test/game_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:word_learn_app/data/game_score.dart' as _i2;
import 'package:word_learn_app/data/settings_repository.dart' as _i7;
import 'package:word_learn_app/data/statistics_repository.dart' as _i6;
import 'package:word_learn_app/data/word_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGameScore_0 extends _i1.SmartFake implements _i2.GameScore {
  _FakeGameScore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordRepository extends _i1.Mock implements _i3.WordRepository {
  MockWordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> insertWord(String? text, String? category) =>
      (super.noSuchMethod(
            Invocation.method(#insertWord, [text, category]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> bulkInsertWords(List<Map<String, dynamic>>? words) =>
      (super.noSuchMethod(
            Invocation.method(#bulkInsertWords, [words]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> isValidWord(String? word) =>
      (super.noSuchMethod(
            Invocation.method(#isValidWord, [word]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> searchCategories(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCategories, [query]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<int> getWordsCount(
    List<String>? categories,
    int? minLength,
    int? maxLength,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWordsCount, [
              categories,
              minLength,
              maxLength,
            ]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<String>> getWords(
    List<String>? categories,
    int? minLength,
    int? maxLength,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWords, [categories, minLength, maxLength]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<int> getWordCount() =>
      (super.noSuchMethod(
            Invocation.method(#getWordCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<String> getWordCategory(String? word) =>
      (super.noSuchMethod(
            Invocation.method(#getWordCategory, [word]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getWordCategory, [word]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> addLearntWord(String? word, String? category) =>
      (super.noSuchMethod(
            Invocation.method(#addLearntWord, [word, category]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLearntWords() =>
      (super.noSuchMethod(
            Invocation.method(#getLearntWords, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> toggleFavorite(String? word, bool? isFav) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [word, isFav]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLearntWord(String? word) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLearntWord, [word]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isWordLearnt(String? word) =>
      (super.noSuchMethod(
            Invocation.method(#isWordLearnt, [word]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [StatisticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsRepository extends _i1.Mock
    implements _i6.StatisticsRepository {
  MockStatisticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GameScore> getScore(String? levelKey) =>
      (super.noSuchMethod(
            Invocation.method(#getScore, [levelKey]),
            returnValue: _i4.Future<_i2.GameScore>.value(
              _FakeGameScore_0(this, Invocation.method(#getScore, [levelKey])),
            ),
          )
          as _i4.Future<_i2.GameScore>);

  @override
  _i4.Future<void> recordGame({
    required String? levelKey,
    required bool? isWin,
    required int? score,
    required int? durationInSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordGame, [], {
              #levelKey: levelKey,
              #isWin: isWin,
              #score: score,
              #durationInSeconds: durationInSeconds,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i7.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSoundEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isSoundEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get isVip =>
      (super.noSuchMethod(Invocation.getter(#isVip), returnValue: false)
          as bool);

  @override
  String get languageCode =>
      (super.noSuchMethod(
            Invocation.getter(#languageCode),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#languageCode),
            ),
          )
          as String);

  @override
  List<String> get defaultCategories =>
      (super.noSuchMethod(
            Invocation.getter(#defaultCategories),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<void> syncSettings() =>
      (super.noSuchMethod(
            Invocation.method(#syncSettings, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSoundEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSoundEnabled, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setVip(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setVip, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLanguageCode(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDefaultCategory(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultCategory, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDefaultCategories(List<String>? values) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultCategories, [values]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
