// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg5wsrfCRFsaeqs8iLg5Mwi2acv9Ktdco',
    appId: '1:818245526732:web:1bea0e77ea1b6553858e69',
    messagingSenderId: '818245526732',
    projectId: 'word-le-earn',
    authDomain: 'word-le-earn.firebaseapp.com',
    storageBucket: 'word-le-earn.firebasestorage.app',
    measurementId: 'G-9KF0RB8TMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzNLIMgocmoy4MONz5cPCIu-KIX-lzhDk',
    appId: '1:818245526732:android:0288892faf5e780f858e69',
    messagingSenderId: '818245526732',
    projectId: 'word-le-earn',
    storageBucket: 'word-le-earn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK0crGFhUGWr9rFMIXm1UQS6C9oIW6jJY',
    appId: '1:818245526732:ios:5773a993135d7c45858e69',
    messagingSenderId: '818245526732',
    projectId: 'word-le-earn',
    storageBucket: 'word-le-earn.firebasestorage.app',
    iosBundleId: 'com.wit4you.wordlearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK0crGFhUGWr9rFMIXm1UQS6C9oIW6jJY',
    appId: '1:818245526732:ios:5773a993135d7c45858e69',
    messagingSenderId: '818245526732',
    projectId: 'word-le-earn',
    storageBucket: 'word-le-earn.firebasestorage.app',
    iosBundleId: 'com.wit4you.wordlearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg5wsrfCRFsaeqs8iLg5Mwi2acv9Ktdco',
    appId: '1:818245526732:web:853ec7aace1e04c5858e69',
    messagingSenderId: '818245526732',
    projectId: 'word-le-earn',
    authDomain: 'word-le-earn.firebaseapp.com',
    storageBucket: 'word-le-earn.firebasestorage.app',
    measurementId: 'G-4PB6X6C4NH',
  );

}